/**
 * Contract: the `fileSearch` IPC surface (043 T054, contracts/file-search-ipc.md).
 *
 * Four independently compiled boundaries meet on these four channel names — the sandboxed preload
 * (emitted as CommonJS and loaded by Electron, so it cannot be imported into this ESM test
 * process), the main-process registrar, the renderer's type declaration, and the renderer store
 * that folds the stream. The BEHAVIOUR behind the scan is proved over a real temp tree by
 * `packages/ui/tests/integration/file-search-scan.integration.test.ts`; what THIS pins is the drift
 * that layer cannot see — a renamed channel, a push broadcast to every window instead of the one
 * that asked, a `generation` gone missing from the wire, or a consumer that folds a superseded
 * run's rows into the current one.
 *
 * It copies `file-index-ipc.contract.test.ts` deliberately, because the channel it is pinning
 * copies `file-index-ipc.ts` deliberately (research R3).
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { MAX_ROWS_PER_BATCH, type ResultRow } from '@throng/core';
import {
  NO_FILE_SEARCH_RESULTS,
  applyFileSearchUpdate,
} from '../../src/renderer/find-in-files/find-in-files-store.js';

function source(relative: string): string {
  return readFileSync(fileURLToPath(new URL(relative, import.meta.url)), 'utf8');
}

const preload = source('../../src/preload/preload.cts');
const mainIpc = source('../../src/main/file-search-ipc.ts');
const service = source('../../src/main/file-search-service.ts');
const mainWiring = source('../../src/main/main.ts');
const globals = source('../../src/renderer/global.d.ts');

/**
 * Just the `fileSearch?:` member of the ambient `window.throng` declaration.
 *
 * The two assertions below used to search the WHOLE file with a character budget —
 * `/fileSearch\?:[\s\S]{0,2400}adoptQuery/` — where the budget stood in for "still inside the
 * fileSearch block". That is a proxy for the thing meant, and it fails on the wrong axis: adding a
 * DOC COMMENT to a field pushes the fields after it past the budget, so a guard about the wire shape
 * goes red for prose that did not change the wire shape. FR-078b did exactly that, to two
 * assertions at once.
 *
 * Slicing the block instead says what was meant. A field found here is inside `fileSearch` by
 * construction, at any distance, and one declared on a NEIGHBOURING interface is not found at all —
 * which is what the budget was protecting and what it did less precisely.
 */
const fileSearchBlock = (): string => {
  const opens = globals.indexOf('fileSearch?: {');
  expect(opens, 'global.d.ts declares no fileSearch member').toBeGreaterThan(-1);
  /*
   * Balance the braces rather than look for the next member's indent. The indent rule was tried
   * first and was wrong in a way worth recording: `fileSearch`'s own fields sit two levels in and
   * its neighbours one, so "the next line at six spaces" reads as a clean boundary — and the
   * declaration nests further than that, so the scan ran straight past the member's end and into
   * `clipboard`. The vacuity check below is what caught it, which is the entire reason it is there.
   *
   * Braces cannot be misread the same way: this declaration is generated by nobody and contains no
   * braces inside strings.
   */
  const from = opens + 'fileSearch?: '.length;
  let depth = 0;
  for (let i = from; i < globals.length; i += 1) {
    if (globals[i] === '{') depth += 1;
    else if (globals[i] === '}') {
      depth -= 1;
      if (depth === 0) return globals.slice(from, i + 1);
    }
  }
  expect.fail('global.d.ts’s fileSearch member has unbalanced braces');
};

function row(relPath: string, from: number): ResultRow {
  return {
    relPath,
    line: 1,
    column: from + 1,
    from,
    to: from + 6,
    snippet: { before: '', matched: 'needle', after: '', truncatedStart: false, truncatedEnd: false },
  };
}

describe('fileSearch IPC contract (043 contracts/file-search-ipc.md)', () => {
  it('names all seven channels, on both sides', () => {
    for (const channel of [
      'throng:fileSearch:start',
      // Round two (FR-078). Its own shape is pinned by `file-search-attach.contract.test.ts`; it is
      // listed here so the channel census stays complete in one place.
      'throng:fileSearch:attach',
      'throng:fileSearch:cancel',
      'throng:fileSearch:drop',
      // Round five (043 FR-091a) — empty a panel's run for every window watching it.
      'throng:fileSearch:clear',
      'throng:fileSearch:update',
      'throng:fileSearch:commit',
    ]) {
      expect(mainIpc, `src/main must name ${channel}`).toContain(channel);
      expect(preload, `the preload must name ${channel}`).toContain(channel);
    }
  });

  it('start is an invoke on both sides and carries the panel, the root, the scope and the term', () => {
    expect(preload).toContain("ipcRenderer.invoke('throng:fileSearch:start'");
    expect(mainIpc).toMatch(/ipcMain\.handle\('throng:fileSearch:start'[\s\S]{0,600}start\(/);
    for (const field of ['panelId', 'projectRoot', 'scopeSubPath', 'term', 'modes']) {
      expect(preload, `the start payload must carry ${field}`).toMatch(
        new RegExp(`fileSearch:[\\s\\S]{0,1200}${field}`),
      );
    }
  });

  it('cancel is a fire-and-forget send on both sides', () => {
    expect(preload).toContain("ipcRenderer.send('throng:fileSearch:cancel'");
    expect(mainIpc).toMatch(/ipcMain\.on\('throng:fileSearch:cancel'[\s\S]{0,400}cancel\(/);
  });

  it('drop is a channel of its own, and releases the run rather than abandoning the scan', () => {
    /*
     * Two channels because they are two questions. `cancel` early-returns for a scan that is no
     * longer running, which is how a panel is USUALLY closed, so a service that only heard `cancel`
     * kept every finished run's per-file stamps for the life of the window and re-stated them on
     * every watcher tick.
     */
    expect(preload).toContain("ipcRenderer.send('throng:fileSearch:drop'");
    expect(mainIpc).toMatch(/ipcMain\.on\('throng:fileSearch:drop'[\s\S]{0,400}drop\(/);
    expect(globals).toContain('drop: (panelId: string) => void;');
  });

  it('clear is a channel of its own — the panel stays, its rows go in every window (FR-091a)', () => {
    /*
     * Neither sibling will do. `cancel` KEEPS the rows a synced view is showing; `drop` detaches only
     * the asking window and releases the run on the last detach, which would let the next scan
     * restart its generation below what every renderer has already seen.
     */
    expect(preload).toContain("ipcRenderer.send('throng:fileSearch:clear'");
    expect(mainIpc).toMatch(/ipcMain\.on\('throng:fileSearch:clear'[\s\S]{0,800}clear\(/);
    expect(globals).toContain('clear: (panelId: string) => void;');
  });

  /*
   * ══ SUPERSEDED (2026-09-09) BY FR-078 / R23 ══
   *
   * This asserted that a run was keyed by `(webContentsId, panelId)` — the composite key introduced
   * because a sub-workspace's synced view is the same panel id in a second window, so keyed by the id
   * alone, closing the mirror aborted the parent's scan and a search typed in the mirror redirected
   * the parent's updates to it.
   *
   * The key is now `panelId`, and the window identity lives in the run's `viewers` set
   * (contracts/file-search-ipc.md, "The keying rule — superseded"). Both original failures are
   * answered without it — the first by reference counting, and the second by ceasing to be a failure,
   * since under FR-078 the mirror IS the panel — and keeping the key made US5 scenario 6 unreachable
   * (#380): a mirrored panel with no run of its own showed an empty list.
   *
   * What the key really protected is asserted below, because it is the half that did not move.
   */
  it('a run is keyed by the panel, and the windows watching it are a SET (FR-078)', () => {
    expect(service).toMatch(/private readonly runs = new Map<string, ScanRun>\(\)/);
    expect(service).toMatch(/readonly viewers: Set<number>;/);
    expect(service).not.toMatch(/function runKey\(/);
    // Never reassigned: `supersede` used to point an existing run at whichever window asked last, and
    // an ADDITION to the set is what replaced that.
    expect(service).not.toMatch(/\.webContentsId\s*=\s*webContentsId/);
    expect(service).toMatch(/existing\.viewers\.add\(webContentsId\)/);
  });

  it('one window’s gesture still cannot reach a scan it is not watching (FR-018)', () => {
    // The half of the composite key worth keeping. Every gesture is still (window, panel), and the
    // window must be in the run's viewer set for cancel to reach it.
    expect(service).toMatch(/cancel\(webContentsId: number, panelId: string\)/);
    expect(service).toMatch(/drop\(webContentsId: number, panelId: string\)/);
    expect(service).toMatch(/!run\.viewers\.has\(webContentsId\)/);
  });

  it('the subscriber for cancel, drop and clear is event.sender too, never payload-supplied', () => {
    for (const channel of ['cancel', 'drop', 'clear']) {
      expect(mainIpc).toMatch(
        new RegExp(`ipcMain\\.on\\('throng:fileSearch:${channel}'[\\s\\S]{0,600}event\\.sender\\.id`),
      );
    }
  });

  it('commit is an invoke on both sides — the one call that writes', () => {
    expect(preload).toContain("ipcRenderer.invoke('throng:fileSearch:commit'");
    expect(mainIpc).toMatch(/ipcMain\.handle\('throng:fileSearch:commit'/);
  });

  it('the update subscription returns an unsubscriber, like every other push channel', () => {
    expect(preload).toContain("ipcRenderer.on('throng:fileSearch:update'");
    expect(preload).toContain("removeListener('throng:fileSearch:update'");
    expect(globals).toContain('fileSearch?:');
    expect(fileSearchBlock()).toMatch(/onUpdate:[\s\S]*=>\s*\(\)\s*=>\s*void/);
  });

  it('pushes reach the SUBSCRIBING webContents only, never a broadcast', () => {
    /*
     * Two panels in two windows over two projects must not see each other's rows (FR-018). The
     * registrar and the service both have to be clean: a broadcast in either defeats the other.
     *
     * Unchanged by FR-078, which widened the recipients from one window to the run's registered
     * viewers and NOT to every window — see `file-search-attach.contract.test.ts` for why the house
     * broadcast was rejected here on Principle I. The comments are stripped because round two names
     * both mechanisms in prose in order to record that they were rejected.
     */
    const code = (text: string): string =>
      text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
    expect(code(mainIpc)).not.toContain('broadcastToWindows');
    expect(code(service)).not.toContain('broadcastToWindows');
    expect(code(mainIpc)).not.toContain('getAllWindows');
    expect(mainIpc).toMatch(/webContents\.fromId\(/);
  });

  it('the subscriber is event.sender, never payload-supplied', () => {
    // A renderer-supplied webContents id would let one window stream another window's project.
    expect(mainIpc).toContain('event.sender.id');
    expect(mainIpc).not.toMatch(/webContentsId\s*[:=]\s*(payload|req|request)\b/);
  });

  it('every update carries a mandatory generation', () => {
    // Not optional, on the wire or in the type: supersession is free ONLY because the consumer can
    // tell which run an update belongs to, and an update without one is unattributable.
    expect(service).toMatch(/generation:\s*number;/);
    expect(service).not.toMatch(/generation\?:/);
  });

  it('the batch bound comes from the named constants, not from an inlined number', () => {
    // "size-bounded" is a property no implementation can fail; a named constant is what makes
    // SC-004's scan half assertable.
    expect(service).toContain('MAX_ROWS_PER_BATCH');
    expect(service).toContain('BATCH_FLUSH_MS');
    expect(service).not.toMatch(/\b250\b/);
    expect(service).not.toMatch(/\browsPerBatch\s*=\s*\d/);
  });

  it('the update payload declares the whole wire shape on the renderer side', () => {
    for (const field of [
      'panelId',
      'generation',
      'status',
      'rows',
      'totalMatches',
      'filesScanned',
      'skipped',
      // 043 T078 — now asserted. It has a producer: `FileSearchService.noteDirectoryChanged`,
      // driven by the EXISTING `throng:files:changed` watch rather than by a watcher of its own
      // (FR-045d). Until that landed it was deliberately left out, because a wire field nothing
      // sends is the one-way channel `ipc-bridge-parity` exists to catch.
      'staleFiles',
      // 043 FR-078b. Same reasoning as `staleFiles` above and the same bar: it has a producer,
      // `FileSearchService.queryFor`, spread into every payload bound for a window that is not the
      // run's originator. A wire field nothing sends is exactly what this file exists to catch.
      'adoptQuery',
    ]) {
      expect(fileSearchBlock(), `the fileSearch update payload must declare ${field}`).toContain(
        field,
      );
    }

    /*
     * And the slice is a slice. If `fileSearchBlock()` ever returned the whole file — a renamed
     * member, a re-indent, a `search` that finds nothing — every assertion above would pass by
     * finding these names somewhere else entirely, and this guard would quietly stop guarding.
     * `clipboard` is the member declared immediately after `fileSearch`, so it is the cheapest
     * possible proof that the end of the block was actually found.
     */
    expect(fileSearchBlock(), 'the fileSearch slice ran past its own member').not.toContain(
      'clipboard',
    );
    expect(fileSearchBlock().length, 'the fileSearch slice is implausibly short').toBeGreaterThan(
      500,
    );
  });

  it('the service is constructed in the composition root and released with its window', () => {
    expect(mainWiring).toContain('new FileSearchService(');
    expect(mainWiring).toContain('registerFileSearchIpc(');
    expect(mainWiring).toMatch(/once\('destroyed',\s*\(\)\s*=>\s*\w+\.release\(\w+\.id\)/);
  });

  it('the consumer DROPS an update from a superseded generation', () => {
    // The race guard the whole design rests on: an in-flight batch from the abandoned run must not
    // land in the surviving run's list. There is no cancel handshake precisely because of this.
    const current = applyFileSearchUpdate(NO_FILE_SEARCH_RESULTS, {
      panelId: 'p',
      generation: 2,
      status: 'running',
      rows: [row('b.ts', 0)],
      totalMatches: 1,
    });
    const late = applyFileSearchUpdate(current, {
      panelId: 'p',
      generation: 1,
      status: 'complete',
      rows: [row('a.ts', 0), row('a.ts', 20)],
      totalMatches: 2,
    });
    expect(late).toBe(current);
    expect(late.rows).toHaveLength(1);
    expect(late.status).toBe('running');
    expect(late.generation).toBe(2);
  });

  it('a NEWER generation replaces the list rather than appending to it', () => {
    const first = applyFileSearchUpdate(NO_FILE_SEARCH_RESULTS, {
      panelId: 'p',
      generation: 1,
      status: 'running',
      rows: [row('a.ts', 0)],
      totalMatches: 1,
    });
    const next = applyFileSearchUpdate(first, {
      panelId: 'p',
      generation: 2,
      status: 'running',
      rows: [row('b.ts', 0)],
      totalMatches: 1,
    });
    expect(next.rows.map((r) => r.relPath)).toEqual(['b.ts']);
    expect(next.generation).toBe(2);
  });

  it('no batch the consumer is asked to accept may exceed the bound', () => {
    // Stated here as well as in the producer's integration test, because this is the size the
    // renderer half is measured against and the two must not drift apart silently.
    expect(MAX_ROWS_PER_BATCH).toBe(250);
    expect(service).toMatch(/MAX_ROWS_PER_BATCH/);
  });
});
