import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it, expect } from 'vitest';

/**
 * Every E2E test carries exactly one significance tag and at least one category tag
 * (034 FR-052/FR-053/FR-054, constitution v5.0.0 Principle V).
 *
 * ══ WHY THIS IS THE GUARD THAT REPLACED A PLAN FILE ══
 *
 * The deleted `shard-plan.json` guard existed for one property: a spec listed nowhere runs nowhere,
 * and does so SILENTLY. That property matters more than any balance, and it now belongs here —
 * checked per TEST rather than per file, which is strictly stronger, because a file could always be
 * listed while one of its tests was unreachable.
 *
 * ══ WHY IT WALKS THE DIRECTORY ══
 *
 * It DISCOVERS the tests rather than checking a list someone maintains. A guard that reads an
 * enumeration passes contentedly while an untagged file sits beside the enumeration — which is the
 * exact failure it is supposed to prevent. Same reasoning as `notice-models.test.ts` and
 * `icon-call-sites.test.ts`.
 *
 * ══ WHY A REGEX AND NOT A PARSER ══
 *
 * The shapes are uniform and generated by a codemod: `test('…', { tag: [...] }, …)` at the start of
 * a line, or `adminTest('…', …)` which tags via its helper. A TypeScript parse would be more
 * faithful and would also make this guard the slowest thing in the unit suite. If the shapes ever
 * stop being uniform, the untagged-test assertion below fails loudly rather than quietly passing.
 */
const E2E_DIR = join(process.cwd(), 'packages', 'ui', 'tests', 'e2e');

const SIGNIFICANCE = ['@core', '@extended'] as const;

/** Closed on purpose: an open vocabulary is one typo from a category nobody ever selects. */
const CATEGORIES = [
  '@boot',
  '@terminal',
  '@editor',
  '@explorer',
  '@prefs',
  '@window',
  '@persistence',
  '@failure',
] as const;

/**
 * One per entry in the constitution's enumerated E2E reserve (v5.3.0 Principle V, 035 FR-016).
 *
 * ══ WHY A TEST NAMES THE ENTRY IT RELIES ON ══
 *
 * The significance tag says which lane a test runs in; the category says what area it covers.
 * Neither can detect a test whose JUSTIFICATION has decayed — and 035's census found that class
 * repeatedly. `tree-drop-open.e2e.ts` justified all five of its tests by the OS drag-and-drop
 * reserve while dispatching a synthetic in-page `throng:tree-drop` CustomEvent, which jsdom
 * reproduces identically. `subtree-expand-collapse.e2e.ts` claimed the native-menu reserve for an
 * in-document React menu. Both claims were true when written and rotted in silence.
 *
 * Naming the entry does not by itself prove the claim — a reviewer still has to check it against
 * what the test drives. What it does is make that check take seconds instead of requiring the
 * whole file to be read, and make the drifted claim a visible string rather than an absence.
 *
 * ══ WHY THE IDENTIFIER IS STABLE AND THE PROSE IS NOT ══
 *
 * These identifiers never change; the constitution's descriptions of them can. v5.3.0 reworded the
 * layout entry to cover resolved colour and cascaded style, and not one test needed editing —
 * which is the entire argument for a tag over a quoted sentence.
 */
const RESERVE = [
  '@reserve:window', // real window lifecycle and multi-window behaviour
  '@reserve:focus', // focus and z-order across windows
  '@reserve:native', // native menus and dialogs
  '@reserve:osdrag', // OS drag-and-drop
  '@reserve:pty', // PTY/ConPTY keyboard and rendering fidelity
  '@reserve:process', // process-tree hygiene
  '@reserve:layout', // real layout and rendered appearance (geometry, colour, cascade)
  '@reserve:input', // real keyboard and input dispatch
  '@reserve:runtime', // real application-runtime identity
] as const;

/** The constitutional ceiling on the lane that gates every push. */
const CORE_CAP = 50;

interface Declared {
  file: string;
  line: number;
  title: string;
  tags: string[];
}

/**
 * Every `test(...)` / `adminTest(...)` declaration, with whatever tag array follows its title.
 * `adminTest` declarations carry no inline options — their tags come from the helper in `admin.ts`,
 * which is read once and applied to them, so the helper cannot drift from this guard unnoticed.
 */
function declarations(): Declared[] {
  const adminSrc = readFileSync(join(E2E_DIR, 'admin.ts'), 'utf8');
  const adminTags = [...(adminSrc.match(/test\(title, \{ tag: \[([^\]]*)\] \}/)?.[1] ?? '').matchAll(/'([^']+)'/g)].map(
    (m) => m[1] as string,
  );

  const out: Declared[] = [];
  for (const file of readdirSync(E2E_DIR).filter((f) => f.endsWith('.e2e.ts'))) {
    const lines = readFileSync(join(E2E_DIR, file), 'utf8').split('\n');
    lines.forEach((text, i) => {
      const decl = /^\s*(adminTest|test)\(\s*(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)"|`((?:[^`\\]|\\.)*)`)\s*,\s*(\{[^}]*\})?/.exec(
        text,
      );
      if (!decl) return;
      const [, fn, s1, s2, s3, opts] = decl;
      const title = s1 ?? s2 ?? s3 ?? '(untitled)';
      // The colon in `@reserve:layout` is why this is not `/'(@[a-z]+)'/g`. With the narrower
      // pattern every reserve tag is INVISIBLE to the guard that exists to enforce it — the
      // assertions below would pass on a suite where nobody had tagged anything.
      const tags =
        fn === 'adminTest'
          ? adminTags
          : [...(opts ?? '').matchAll(/'(@[a-z][a-z:]*)'/g)].map((m) => m[1] as string);
      out.push({ file, line: i + 1, title, tags });
    });
  }
  return out;
}

const all = declarations();

describe('E2E significance and category tags', () => {
  it('finds the tests at all', () => {
    // If the declaration shapes change, every assertion below would pass vacuously on an empty
    // set. This is the assertion that stops that — the guard has to prove it found something.
    expect(all.length).toBeGreaterThan(100);
  });

  it('gives every test exactly one significance tag', () => {
    const offenders = all
      .map((d) => ({ ...d, sig: d.tags.filter((t) => (SIGNIFICANCE as readonly string[]).includes(t)) }))
      .filter((d) => d.sig.length !== 1)
      .map((d) => `${d.file}:${d.line} "${d.title}" has ${d.sig.length ? d.sig.join(' + ') : 'no significance tag'}`);
    expect(
      offenders,
      `every E2E test needs exactly one of @core / @extended. With none it runs in NEITHER lane and ` +
        `nobody would notice; with both it runs twice at release and is counted twice.\n  ` +
        `${offenders.join('\n  ')}`,
    ).toEqual([]);
  });

  it('gives every test at least one category tag from the closed vocabulary', () => {
    const offenders = all
      .filter((d) => !d.tags.some((t) => (CATEGORIES as readonly string[]).includes(t)))
      .map((d) => `${d.file}:${d.line} "${d.title}"`);
    expect(
      offenders,
      `every E2E test needs a category so an area can be run without naming files. Valid: ` +
        `${CATEGORIES.join(' ')}\n  ${offenders.join('\n  ')}`,
    ).toEqual([]);
  });

  it('reads a colon-bearing tag at all', () => {
    // The regex above is the single point of failure for everything below: narrow it and the
    // reserve assertions pass vacuously on an untagged suite. This proves it can see one.
    const sample = [...`{ tag: ['@core', '@reserve:layout'] }`.matchAll(/'(@[a-z][a-z:]*)'/g)].map((m) => m[1]);
    expect(sample).toContain('@reserve:layout');
  });

  it('never gives a test more than one reserve entry', () => {
    // Unconditional from day one: a test naming two entries is asserting two things and should be
    // split. Nothing has to be migrated first for this to hold.
    const offenders = all
      .map((d) => ({ ...d, res: d.tags.filter((t) => (RESERVE as readonly string[]).includes(t)) }))
      .filter((d) => d.res.length > 1)
      .map((d) => `${d.file}:${d.line} "${d.title}" names ${d.res.join(' + ')}`);
    expect(
      offenders,
      `a test that appears to need two reserve entries is asserting two things (035 FR-016b). ` +
        `Split it rather than tagging it twice.\n  ${offenders.join('\n  ')}`,
    ).toEqual([]);
  });

  it('drives the untagged count down and never lets it rise', () => {
    /**
     * ══ WHY A RATCHET AND NOT A FLAT REQUIREMENT ══
     *
     * FR-016 requires every E2E test to name its reserve entry. 687 of them do not yet, and the
     * honest way to close that is by READING each test — not by inferring the tag from its source.
     *
     * That is not a preference; it was measured. A codemod over the whole suite tagged 443 tests
     * and put 205 under `@reserve:input`, because `.press(` and `.type(` appear in nearly every
     * spec here — a test that types into an editor to check what lands on disk makes no claim
     * about input dispatch. Restricting it to "unambiguous" APIs did no better: it read
     * `process.execPath` out of `terminal-reattach.e2e.ts`'s daemon SETUP and called the test a
     * runtime-identity claim, and it read `DataTransfer` out of a body whose test actually drives
     * the synthetic `dropPaths()` helper.
     *
     * The reason is general, and it is why no smarter regex would fix it: **the evidence for a
     * test's CLAIM is not lexically distinguishable from the evidence for its SETUP.** An
     * automated tag is therefore a confident-looking false justification — the precise defect this
     * tag exists to eliminate, reintroduced by the tool meant to prevent it.
     *
     * So the count falls as tests are read, and this ratchet makes sure it only ever falls. It
     * fails BOTH ways, exactly like `e2e-budget.json`: over the recorded debt, and under it without
     * the record being re-seeded, so progress cannot be quietly banked or quietly lost.
     */
    const untagged = all.filter((d) => !d.tags.some((t) => (RESERVE as readonly string[]).includes(t)));
    const recorded = JSON.parse(
      readFileSync(join(E2E_DIR, 'reserve-tag-debt.json'), 'utf8'),
    ) as { untagged: number };

    expect(
      untagged.length,
      `${untagged.length} E2E tests do not name a reserve entry, against a recorded debt of ` +
        `${recorded.untagged}. This number may fall and MUST NOT rise: a new E2E test names its ` +
        `entry, and one that cannot is a test that should not be at this layer.`,
    ).toBeLessThanOrEqual(recorded.untagged);

    expect(
      untagged.length,
      `the recorded debt is ${recorded.untagged} but only ${untagged.length} tests are untagged. ` +
        `Re-seed reserve-tag-debt.json in the commit that tagged them, or the ratchet silently ` +
        `stops ratcheting.`,
    ).toEqual(recorded.untagged);
  });

  it('uses no category outside the vocabulary', () => {
    const known = new Set<string>([...SIGNIFICANCE, ...CATEGORIES, ...RESERVE, '@admin', '@quarantine']);
    const offenders = all
      .flatMap((d) => d.tags.filter((t) => !known.has(t)).map((t) => `${d.file}:${d.line} ${t}`))
      .sort();
    expect(
      offenders,
      `an open vocabulary is one typo away from a category nobody ever selects. Valid: ` +
        `${[...known].join(' ')}\n  ${offenders.join('\n  ')}`,
    ).toEqual([]);
  });

  it('keeps the critical lane at or under its cap', () => {
    const core = all.filter((d) => d.tags.includes('@core'));
    expect(
      core.length,
      `@core holds ${core.length} tests against a cap of ${CORE_CAP}. The critical selection gates ` +
        `every push; a test earns a place in it by what breaking it costs a USER, not by what ` +
        `running it costs a machine. Demote the weakest to @extended.`,
    ).toBeLessThanOrEqual(CORE_CAP);
  });

  it('does not put an elevation-gated test in the lane that gates merges', () => {
    // @admin tests skip unless the process is elevated, and the critical lane runs unelevated.
    // One in @core would be a permanent skip inside the gate — coverage that looks green and is not.
    const offenders = all
      .filter((d) => d.tags.includes('@admin') && d.tags.includes('@core'))
      .map((d) => `${d.file}:${d.line} "${d.title}"`);
    expect(offenders, `@admin tests cannot execute in the unelevated CI lane:\n  ${offenders.join('\n  ')}`).toEqual(
      [],
    );
  });
});
