import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it, expect } from 'vitest';

/**
 * Every E2E test carries exactly one significance tag and at least one category tag
 * (034 FR-052/FR-053/FR-054, constitution v5.0.0 Principle V).
 *
 * ══ WHY THIS IS THE GUARD THAT REPLACED A PLAN FILE ══
 *
 * The deleted `shard-plan.json` guard existed for one property: a spec listed nowhere runs nowhere,
 * and does so SILENTLY. That property matters more than any balance, and it now belongs here —
 * checked per TEST rather than per file, which is strictly stronger, because a file could always be
 * listed while one of its tests was unreachable.
 *
 * ══ WHY IT WALKS THE DIRECTORY ══
 *
 * It DISCOVERS the tests rather than checking a list someone maintains. A guard that reads an
 * enumeration passes contentedly while an untagged file sits beside the enumeration — which is the
 * exact failure it is supposed to prevent. Same reasoning as `notice-models.test.ts` and
 * `icon-call-sites.test.ts`.
 *
 * ══ WHY A REGEX AND NOT A PARSER ══
 *
 * The shapes are uniform and generated by a codemod: `test('…', { tag: [...] }, …)` at the start of
 * a line, or `adminTest('…', …)` which tags via its helper. A TypeScript parse would be more
 * faithful and would also make this guard the slowest thing in the unit suite. If the shapes ever
 * stop being uniform, the untagged-test assertion below fails loudly rather than quietly passing.
 */
const E2E_DIR = join(process.cwd(), 'packages', 'ui', 'tests', 'e2e');

const SIGNIFICANCE = ['@core', '@extended'] as const;

/** Closed on purpose: an open vocabulary is one typo from a category nobody ever selects. */
const CATEGORIES = [
  '@boot',
  '@terminal',
  '@editor',
  '@explorer',
  '@prefs',
  '@window',
  '@persistence',
  '@failure',
] as const;

/** The constitutional ceiling on the lane that gates every push. */
const CORE_CAP = 50;

interface Declared {
  file: string;
  line: number;
  title: string;
  tags: string[];
}

/**
 * Every `test(...)` / `adminTest(...)` declaration, with whatever tag array follows its title.
 * `adminTest` declarations carry no inline options — their tags come from the helper in `admin.ts`,
 * which is read once and applied to them, so the helper cannot drift from this guard unnoticed.
 */
function declarations(): Declared[] {
  const adminSrc = readFileSync(join(E2E_DIR, 'admin.ts'), 'utf8');
  const adminTags = [...(adminSrc.match(/test\(title, \{ tag: \[([^\]]*)\] \}/)?.[1] ?? '').matchAll(/'([^']+)'/g)].map(
    (m) => m[1] as string,
  );

  const out: Declared[] = [];
  for (const file of readdirSync(E2E_DIR).filter((f) => f.endsWith('.e2e.ts'))) {
    const lines = readFileSync(join(E2E_DIR, file), 'utf8').split('\n');
    lines.forEach((text, i) => {
      const decl = /^\s*(adminTest|test)\(\s*(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)"|`((?:[^`\\]|\\.)*)`)\s*,\s*(\{[^}]*\})?/.exec(
        text,
      );
      if (!decl) return;
      const [, fn, s1, s2, s3, opts] = decl;
      const title = s1 ?? s2 ?? s3 ?? '(untitled)';
      const tags =
        fn === 'adminTest'
          ? adminTags
          : [...(opts ?? '').matchAll(/'(@[a-z]+)'/g)].map((m) => m[1] as string);
      out.push({ file, line: i + 1, title, tags });
    });
  }
  return out;
}

const all = declarations();

describe('E2E significance and category tags', () => {
  it('finds the tests at all', () => {
    // If the declaration shapes change, every assertion below would pass vacuously on an empty
    // set. This is the assertion that stops that — the guard has to prove it found something.
    expect(all.length).toBeGreaterThan(100);
  });

  it('gives every test exactly one significance tag', () => {
    const offenders = all
      .map((d) => ({ ...d, sig: d.tags.filter((t) => (SIGNIFICANCE as readonly string[]).includes(t)) }))
      .filter((d) => d.sig.length !== 1)
      .map((d) => `${d.file}:${d.line} "${d.title}" has ${d.sig.length ? d.sig.join(' + ') : 'no significance tag'}`);
    expect(
      offenders,
      `every E2E test needs exactly one of @core / @extended. With none it runs in NEITHER lane and ` +
        `nobody would notice; with both it runs twice at release and is counted twice.\n  ` +
        `${offenders.join('\n  ')}`,
    ).toEqual([]);
  });

  it('gives every test at least one category tag from the closed vocabulary', () => {
    const offenders = all
      .filter((d) => !d.tags.some((t) => (CATEGORIES as readonly string[]).includes(t)))
      .map((d) => `${d.file}:${d.line} "${d.title}"`);
    expect(
      offenders,
      `every E2E test needs a category so an area can be run without naming files. Valid: ` +
        `${CATEGORIES.join(' ')}\n  ${offenders.join('\n  ')}`,
    ).toEqual([]);
  });

  it('uses no category outside the vocabulary', () => {
    const known = new Set<string>([...SIGNIFICANCE, ...CATEGORIES, '@admin', '@quarantine']);
    const offenders = all
      .flatMap((d) => d.tags.filter((t) => !known.has(t)).map((t) => `${d.file}:${d.line} ${t}`))
      .sort();
    expect(
      offenders,
      `an open vocabulary is one typo away from a category nobody ever selects. Valid: ` +
        `${[...known].join(' ')}\n  ${offenders.join('\n  ')}`,
    ).toEqual([]);
  });

  it('keeps the critical lane at or under its cap', () => {
    const core = all.filter((d) => d.tags.includes('@core'));
    expect(
      core.length,
      `@core holds ${core.length} tests against a cap of ${CORE_CAP}. The critical selection gates ` +
        `every push; a test earns a place in it by what breaking it costs a USER, not by what ` +
        `running it costs a machine. Demote the weakest to @extended.`,
    ).toBeLessThanOrEqual(CORE_CAP);
  });

  it('does not put an elevation-gated test in the lane that gates merges', () => {
    // @admin tests skip unless the process is elevated, and the critical lane runs unelevated.
    // One in @core would be a permanent skip inside the gate — coverage that looks green and is not.
    const offenders = all
      .filter((d) => d.tags.includes('@admin') && d.tags.includes('@core'))
      .map((d) => `${d.file}:${d.line} "${d.title}"`);
    expect(offenders, `@admin tests cannot execute in the unelevated CI lane:\n  ${offenders.join('\n  ')}`).toEqual(
      [],
    );
  });
});
